import type { Metadata } from "next";
import "@ant-design/v5-patch-for-react-19";
import "../antd-compat"; // Import the compatibility fix
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
